package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"time"
)

// runReport is the whole outcome of one run: the measurements, the bounds applied and the metadata a
// reader needs in order to judge whether the numbers are comparable with another machine's.
type runReport struct {
	Command   string       `json:"command"`
	Commit    string       `json:"commit"`
	Date      string       `json:"date"`
	TimeoutMS int64        `json:"timeout_ms"`
	MemCapMiB int64        `json:"mem_cap_mib"`
	Locale    string       `json:"locale"`
	Machine   machineSpec  `json:"machine"`
	Cases     []caseResult `json:"cases"`
	Known     []knownEntry `json:"known_failures"`
	Stale     []string     `json:"stale_known_failures"`
	KnownText string       `json:"-"` // the list is embedded verbatim in the Markdown report
	Notes     string       `json:"-"` // the optional notes file, likewise embedded verbatim
}

// machineSpec is the specification of the machine the measurements come from.
type machineSpec struct {
	CPU    string `json:"cpu"`
	Cores  int    `json:"cores"`
	Memory string `json:"memory"`
	Kernel string `json:"kernel"`
	Go     string `json:"go"`
	Clang  string `json:"clang"`
}

// machineInfo collects the machine description the report carries, tolerating anything unavailable.
func machineInfo() machineSpec {
	return machineSpec{
		CPU:    cpuModel(),
		Cores:  runtime.NumCPU(),
		Memory: memTotal(),
		Kernel: runtime.GOOS + "/" + runtime.GOARCH + " " + kernelRelease(),
		Go:     runtime.Version(),
		Clang:  clangVersion(),
	}
}

// cpuModel reads the processor description from /proc/cpuinfo.
func cpuModel() string {
	return firstValueOf("/proc/cpuinfo", "model name")
}

// memTotal reads the installed memory from /proc/meminfo and renders it in gibibytes.
func memTotal() string {
	fields := strings.Fields(firstValueOf("/proc/meminfo", "MemTotal"))
	if len(fields) < 1 {
		return "unknown"
	}
	kb, err := strconv.ParseFloat(fields[0], 64)
	if err != nil {
		return "unknown"
	}
	return strconv.FormatFloat(kb/1024/1024, 'f', 1, 64) + " GiB"
}

// kernelRelease reads the running kernel's release string.
func kernelRelease() string {
	data, err := os.ReadFile("/proc/sys/kernel/osrelease")
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(data))
}

// clangVersion keeps the first line of `clang --version`, which is the toolchain the compiler links with.
func clangVersion() string {
	out, err := exec.Command("clang", "--version").Output()
	if err != nil {
		return "unavailable"
	}
	return firstLine(string(out))
}

// gitRevision returns the short commit the measurements belong to, so a reader can check out that tree.
func gitRevision() string {
	out, err := exec.Command("git", "rev-parse", "--short", "HEAD").Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}

// firstValueOf returns the value on the first matching line of a /proc style key/value file, where the
// separator is a colon, a tab or both.
func firstValueOf(path, key string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return "unknown"
	}
	for _, line := range strings.Split(string(data), "\n") {
		rest, ok := strings.CutPrefix(line, key)
		if !ok {
			continue
		}
		if value := strings.TrimSpace(strings.TrimLeft(rest, ": \t")); value != "" {
			return value
		}
	}
	return "unknown"
}

// writeJSON writes the machine-readable results, creating the parent directory.
func writeJSON(path string, rep runReport) error {
	if dir := filepath.Dir(path); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	data, err := json.MarshalIndent(rep, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0o644)
}

// renderMarkdown renders the report: what was run, on what machine, with what outcome, and which
// failures are already documented.
func renderMarkdown(rep runReport) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# QuarkLang stress / robustness report\n\n")
	fmt.Fprintf(&b, "Generated by `qkstress run` at %s from commit `%s` — regenerate it with the commands below\nrather than editing it by hand.\n\n", rep.Date, rep.Commit)
	writeReproduce(&b, rep.Command)
	writeMachine(&b, rep)
	writeResults(&b, rep)
	writeFindings(&b, rep)
	writeKnown(&b, rep)
	writeNotes(&b, rep)
	return b.String()
}

// writeReproduce documents the exact commands that produce the corpus, the measurements and the report.
func writeReproduce(b *strings.Builder, command string) {
	fmt.Fprintf(b, "## How to reproduce\n\n```sh\n")
	fmt.Fprintf(b, "go build -o stress-out/bin/quark .\n")
	fmt.Fprintf(b, "(cd compiler && go build -o ../stress-out/bin/qkc .)\n")
	fmt.Fprintf(b, "go run ./cmd/qkstress gen -out stress-out/cases\n")
	fmt.Fprintf(b, "go run ./cmd/qkstress run -cases stress-out/cases\n")
	fmt.Fprintf(b, "```\n\n")
	fmt.Fprintf(b, "The run that produced this report was invoked as:\n\n```sh\n%s\n```\n\n", command)
	fmt.Fprintf(b, "Every phase is bounded twice: wall clock and peak resident set size of the whole process\n")
	fmt.Fprintf(b, "group (the compiler drives clang, the linker and the linked program as group members). A phase\n")
	fmt.Fprintf(b, "that trips a bound is killed and the case is reported as `TIMEOUT` or `MEMCAP`.\n\n")
}

// writeMachine renders the machine specification and the bounds the run used.
func writeMachine(b *strings.Builder, rep runReport) {
	fmt.Fprintf(b, "## Machine and bounds\n\n")
	fmt.Fprintf(b, "| item | value |\n|---|---|\n")
	fmt.Fprintf(b, "| commit | `%s` |\n", rep.Commit)
	fmt.Fprintf(b, "| CPU | %s |\n", rep.Machine.CPU)
	fmt.Fprintf(b, "| cores | %d |\n", rep.Machine.Cores)
	fmt.Fprintf(b, "| memory | %s |\n", rep.Machine.Memory)
	fmt.Fprintf(b, "| kernel | %s |\n", rep.Machine.Kernel)
	fmt.Fprintf(b, "| Go | %s |\n", rep.Machine.Go)
	fmt.Fprintf(b, "| clang | %s |\n", rep.Machine.Clang)
	fmt.Fprintf(b, "| locale | `%s` for both engines |\n", rep.Locale)
	fmt.Fprintf(b, "| wall-clock bound | %s per phase |\n", time.Duration(rep.TimeoutMS)*time.Millisecond)
	fmt.Fprintf(b, "| memory ceiling | %d MiB per phase |\n", rep.MemCapMiB)
	fmt.Fprintf(b, "| compiler cache | cold per case |\n\n")
}

// writeResults renders the measured table and the verdict histogram.
func writeResults(b *strings.Builder, rep runReport) {
	fmt.Fprintf(b, "## Results\n\n")
	fmt.Fprintf(b, "`interp` / `qkc gen` / `qkc run` are wall-clock seconds; `peak RSS` is the largest group figure seen in\n")
	fmt.Fprintf(b, "either engine's run phase; `exits` are the two run exit statuses (interpreter / compiler); `pos` says\n")
	fmt.Fprintf(b, "whether that engine's stderr carried a source position.\n\n")
	fmt.Fprintf(b, "| case | category | bytes | interp s | qkc gen s | qkc run s | peak RSS MiB i/c | exits i/c | pos i/c | verdict |\n")
	fmt.Fprintf(b, "|---|---|---:|---:|---:|---:|---|---|---|---|\n")
	for _, r := range rep.Cases {
		fmt.Fprintf(b, "| `%s` | %s | %d | %s | %s | %s | %s/%s | %s | %s/%s | %s |\n",
			r.Name, r.Category, r.Bytes,
			r.Interp.Run.seconds(), r.Compiler.Front.seconds(), r.Compiler.Run.seconds(),
			r.Interp.Run.peakMiB(), r.Compiler.Run.peakMiB(),
			r.exitPair(), positionMark(r.Interp.Run.Stderr), positionMark(r.Compiler.Run.Stderr),
			verdictLabel(r))
	}
	fmt.Fprintf(b, "\n")
	counts := map[string]int{}
	for _, r := range rep.Cases {
		counts[r.Verdict]++
	}
	keys := sortedKeys(counts)
	fmt.Fprintf(b, "| verdict | cases | meaning |\n|---|---:|---|\n")
	for _, k := range keys {
		fmt.Fprintf(b, "| %s | %d | %s |\n", k, counts[k], verdictMeaning(k))
	}
	if len(rep.Stale) > 0 {
		fmt.Fprintf(b, "\n⚠ stale known-failure entries (the case no longer fails, remove them): %s\n", strings.Join(rep.Stale, ", "))
	}
	fmt.Fprintf(b, "\n")
}

// verdictMeaning explains one verdict for the report's legend.
func verdictMeaning(verdict string) string {
	switch verdict {
	case VerdictAgree:
		return "both engines accepted the source and produced identical output and exit status"
	case VerdictRejectAgree:
		return "both engines rejected the source with identical diagnostics"
	case VerdictRejectDiff:
		return "both engines rejected the source, with different wording (information only, does not fail the run)"
	case VerdictDiverge:
		return "at least one engine accepted the source and the run outcomes differ"
	case VerdictAcceptMismatch:
		return "one front end accepted the source and the other rejected it"
	case VerdictPanic:
		return "a Go runtime crash surfaced in one of the engines"
	case VerdictTimeout:
		return "a phase outlived the wall-clock bound and was killed"
	case VerdictMemCap:
		return "a phase outlived the memory ceiling and was killed"
	}
	return "unknown verdict"
}

// sortedKeys returns a map's keys in a stable order.
func sortedKeys(m map[string]int) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// writeFindings renders one block per loud case plus the informative reject-difference cases.
func writeFindings(b *strings.Builder, rep runReport) {
	var loud, info []caseResult
	for _, r := range rep.Cases {
		switch {
		case r.loud():
			loud = append(loud, r)
		case r.Verdict == VerdictRejectDiff:
			info = append(info, r)
		}
	}
	fmt.Fprintf(b, "## Findings\n\n")
	if len(loud) == 0 {
		fmt.Fprintf(b, "No loud findings: every case either agreed between the two engines or was rejected cleanly by both.\n\n")
	} else {
		fmt.Fprintf(b, "%d loud finding(s) — a panic, a bound being hit, a front-end mismatch or a run-outcome\n", len(loud))
		fmt.Fprintf(b, "divergence. A finding marked *known* is listed in `stress/known-failures.txt` and does not fail the run.\n\n")
		for _, r := range loud {
			writeFinding(b, r)
		}
	}
	if len(info) > 0 {
		fmt.Fprintf(b, "### Rejected by both engines with different wording\n\n")
		for _, r := range info {
			fmt.Fprintf(b, "- `%s`: interpreter says %s; compiler says %s\n", r.Name,
				quoteOf(firstLine(r.Interp.Front.Stderr)), quoteOf(firstLine(r.Compiler.Front.Stderr)))
		}
		fmt.Fprintf(b, "\n")
	}
}

// writeFinding renders one loud case: what it stresses, what each engine did and why it is (not) known.
func writeFinding(b *strings.Builder, r caseResult) {
	status := "**new**"
	if r.Known {
		status = "known"
	}
	fmt.Fprintf(b, "### %s — %s (%s)\n\n", r.Name, r.Verdict, status)
	fmt.Fprintf(b, "%s\n\n", r.Doc)
	fmt.Fprintf(b, "| engine | phase | exit | wall s | peak RSS MiB | bounded |\n|---|---|---:|---:|---|---|\n")
	writePhaseRow(b, "interpreter", "front end", r.Interp.Front)
	writePhaseRow(b, "interpreter", "run", r.Interp.Run)
	writePhaseRow(b, "compiler", "IR generation", r.Compiler.Front)
	writePhaseRow(b, "compiler", "run", r.Compiler.Run)
	fmt.Fprintf(b, "\n")
	if r.Interp.Accepted != r.Compiler.Accepted {
		fmt.Fprintf(b, "Front-end acceptance differs: interpreter %v, compiler %v.\n\n", r.Interp.Accepted, r.Compiler.Accepted)
	}
	for _, phase := range []struct {
		label string
		res   probeResult
	}{{"interpreter", r.Interp.Run}, {"compiler", r.Compiler.Run}, {"compiler front end", r.Compiler.Front}} {
		if line := firstLine(phase.res.Stderr); line != "" {
			fmt.Fprintf(b, "- %s stderr: `%s`\n", phase.label, quoteOf(line))
		}
	}
	if r.Known {
		fmt.Fprintf(b, "- documented as: %s\n", r.Reason)
	}
	fmt.Fprintf(b, "\n")
}

// writePhaseRow renders one bounded phase inside a finding.
func writePhaseRow(b *strings.Builder, engine, phase string, res probeResult) {
	bounded := "no"
	switch {
	case res.TimedOut:
		bounded = "timeout"
	case res.MemCapped:
		bounded = "memory ceiling"
	case res.Panicked:
		bounded = "go panic"
	}
	fmt.Fprintf(b, "| %s | %s | %d | %s | %s | %s |\n", engine, phase, res.Exit, res.seconds(), res.peakMiB(), bounded)
}

// writeKnown embeds the known-failure list verbatim, so the report and the allow-list cannot drift.
func writeKnown(b *strings.Builder, rep runReport) {
	fmt.Fprintf(b, "## Known failures, verbatim from `%s`\n\n", "stress/known-failures.txt")
	if strings.TrimSpace(rep.KnownText) == "" {
		fmt.Fprintf(b, "The list is empty: no defect is currently documented as known.\n")
		return
	}
	fmt.Fprintf(b, "```\n%s```\n", rep.KnownText)
}

// writeNotes appends the tracked notes file verbatim, which is where the measurements a runner cannot
// make by itself live (cost curves, near-misses, out-of-scope work).
func writeNotes(b *strings.Builder, rep runReport) {
	if strings.TrimSpace(rep.Notes) == "" {
		return
	}
	fmt.Fprintf(b, "\n")
	fmt.Fprintf(b, "%s", rep.Notes)
}
