package i18n

// Generated by the table split: the lint domain translations (Chinese template -> English).
// Keys are the exact templates used at the call sites; TestTemplatesRegistered fails when one is missing.
var lintTable = map[string]string{

	"%s %s 遮蔽外层同名变量（外层声明于第 %d 行）":                     "%s %s shadows an outer variable of the same name (declared on line %d)",
	"%s %s 遮蔽全局函数（同名调用会被解析为该局部变量）":                    "%s %s shadows a global function (calls with that name resolve to this local)",
	"%s %s 只被赋值、从未读取":                                 "%s %s is assigned but never read",
	"%s %s 声明后从未使用":                                   "%s %s is declared but never used",
	"函数 %s 声明返回类型 %s，但存在执行到函数末尾的路径（运行期得到 nil）":        "function %s declares return type %s but has a path that reaches the end of the function (yields nil at runtime)",
	"函数 %s 声明返回类型 %s，但终止路径以 log 结束、不产生返回值（运行期得到 nil）": "function %s declares return type %s but a terminating path ends with log and produces no value (yields nil at runtime)",
	"不可达代码（第 %d 行之后的语句不会执行）":                          "unreachable code (statements after line %d never execute)",
	"自赋值：%s 赋值给自身（无效果）":                               "self-assignment: %s is assigned to itself (no effect)",
	"对 %s 的赋值被第 %d 行的赋值覆盖（其间未读取）":                     "the assignment to %s is overwritten on line %d before any read",
	"while (true) 且循环体内无 break/return：可能的死循环":         "while (true) with no break/return in the body: possible infinite loop",
	"常量除零：%s 0（运行期报错；若为刻意错误处理请放进 try 块）":              "division by a constant zero: %s 0 (runtime error; put it inside a try block if intentional)",
	"自身比较：%s == %s 恒为真":                               "self-comparison: %s == %s is always true",
	"自身比较：%s != %s 恒为假":                               "self-comparison: %s != %s is always false",
	"%s::%s 返回 void，其调用结果被当作值使用（运行期为 nil）":            "%s::%s returns void but its result is used as a value (nil at runtime)",
	"函数 %s 返回 void，其调用结果被当作值使用（运行期为 nil）":             "function %s returns void but its result is used as a value (nil at runtime)",
	"%s (true)：条件恒为真，分支永远执行":                          "%s (true): the condition is always true, so the branch always runs",
	"%s (false)：条件恒为假，分支永不执行":                         "%s (false): the condition is always false, so the branch never runs",
	"导入了 %q 但未使用其任何符号（可删除该 import）":                   "imported %q but no symbol from it is used (the import can be removed)",
	"函数 %s 从未被调用（死代码；库文件中的函数不报）":                      "function %s is never called (dead code; functions in library files are exempt)",
	"循环变量":     "loop variable",
	"catch 变量": "catch variable",
	"类型 %s 疑似实现接口 %s，但缺少方法 %s（已实现 %s）": "type %s looks like it implements interface %s but is missing method %s (implemented: %s)",
}
