package i18n

// Generated by the table split: the macro domain translations (Chinese template -> English).
// Keys are the exact templates used at the call sites; TestTemplatesRegistered fails when one is missing.
var macroTable = map[string]string{

	"ParseError: #macro 需要名字，第 %d 行":                  "ParseError: #macro needs a name, line %d",
	"ParseError: #macro %s 缺少参数列表，第 %d 行":             "ParseError: #macro %s is missing its parameter list, line %d",
	"ParseError: #macro %s 参数列表需要 () [] {} 之一，第 %d 行": "ParseError: #macro %s parameter list must use () [] or {}, line %d",
	"ParseError: #macro %s 参数必须是名字（逗号分隔，个数不限），第 %d 行": "ParseError: #macro %s parameters must be names (comma-separated, any count), line %d",
	"ParseError: #macro %s 缺少主体，第 %d 行":               "ParseError: #macro %s is missing its body, line %d",
	"ParseError: #macro %s 主体需要 () [] {} 之一，第 %d 行":   "ParseError: #macro %s body must use () [] or {}, line %d",
	"ParseError: 分隔符不配对，第 %d 行":                       "ParseError: unbalanced delimiters, line %d",
	"ParseError: 宏 %s 需要 %d 个参数，调用给了 %d 个（第 %d 行）":    "ParseError: macro %s expects %d parameters but the call passed %d, line %d",
	"宏 %s 展开失败：%v":                                    "macro %s failed to expand: %v",
	"第 %d 行：# 后必须是预处理命令（when/return/error）":           "line %d: '#' must be followed by a preprocessor command (when/return/error)",
	"第 %d 行：#%s 需要 ( ... )":                           "line %d: #%s requires ( ... )",
	"第 %d 行：#when 需要 (compile|run)":                   "line %d: #when requires (compile|run)",
	"第 %d 行：#when 需要 { ... } 块":                       "line %d: #when requires a { ... } block",
	"第 %d 行：#error 需要 (\"消息\")":                       "line %d: #error requires (\"message\")",
	"第 %d 行：预处理错误 #error(%s)":                         "line %d: #error(%s)",
	"第 %d 行：#insert(#ast(%s))：%s 不是宏参数名":              "line %d: #insert(#ast(%s)): %s is not a macro parameter name",
	"第 %d 行：#execute 需要 (名字)":                         "line %d: #execute requires (name)",
	"第 %d 行：未知预处理命令 #%s":                              "line %d: unknown preprocessor command #%s",
	"#insert 需要 (#ast(名字)) 形式":                        "#insert requires the (#ast(name)) form",
}
