package i18n

// Generated by the table split: the repl domain translations (Chinese template -> English).
// Keys are the exact templates used at the call sites; TestTemplatesRegistered fails when one is missing.
var replTable = map[string]string{

	"REPL: 内部错误（已恢复）: %v":        "REPL: internal error (recovered): %v",
	"已定义 %s":                     "defined %s",
	"已定义 type struct%s %s;":      "defined type struct%s %s;",
	"已定义 type interface%s %s;":   "defined type interface%s %s;",
	"已定义 impl%s %s;（%d 个方法）":     "defined impl%s %s; (%d methods)",
	"已定义 library %s;（%d 个符号）":    "defined library %s; (%d symbols)",
	"已定义 type %s %s;":            "defined type %s %s;",
	"已定义 %s\n":                   "defined %s\n",
	"已定义 type struct%s %s;\n":    "defined type struct%s %s;\n",
	"已定义 type interface%s %s;\n": "defined type interface%s %s;\n",
	"已定义 impl%s %s;（%d 个方法）\n":   "defined impl%s %s; (%d methods)\n",
	"已定义 library %s;（%d 个符号）\n":  "defined library %s; (%d symbols)\n",
	"已定义 type %s %s;\n":          "defined type %s %s;\n",
}
