package i18n

// Generated by the table split: the cli domain translations (Chinese template -> English).
// Keys are the exact templates used at the call sites; TestTemplatesRegistered fails when one is missing.
var cliTable = map[string]string{

	":load 需要一个文件参数":                                                ":load requires a file argument",
	"未知命令 %s（:help 查看帮助）":                                           "unknown command %s (see :help)",
	"-L 需要一个目录参数":                                                   "-L requires a directory argument",
	"usage: qklsp [-L dir]...  （stdio 上提供 LSP 服务）":                  "usage: qklsp [-L dir]...  (serves LSP over stdio)",
	"未知参数 %s":                                                       "unknown argument %s",
	"未打开的文档 %s":                                                     "document not opened: %s",
	"qklsp: 非法 Content-Length %q":                                   "qklsp: invalid Content-Length %q",
	"qklsp: 缺少 Content-Length 头":                                    "qklsp: missing Content-Length header",
	"qklsp: JSON 解析失败: %w":                                          "qklsp: JSON parse failed: %w",
	"qklsp: 未实现的方法 %s":                                              "qklsp: method not implemented: %s",
	"qkcheck: -L 需要一个目录参数":                                          "qkcheck: -L requires a directory argument",
	"qkcheck: 未知参数 %s\n":                                            "qkcheck: unknown argument %s\n",
	"qkcheck: 没有可检查的 .qk 文件":                                        "qkcheck: no .qk files to check",
	"qkcheck: %d 个问题（%d 错误 / %d 警告）\n":                              "qkcheck: %d issue(s) (%d error(s) / %d warning(s))\n",
	"qkdoc: -o 需要一个文件参数":                                            "qkdoc: -o requires a file argument",
	"qkdoc: -title 需要一个参数":                                          "qkdoc: -title requires an argument",
	"qkdoc: 未知参数 %s\n":                                              "qkdoc: unknown argument %s\n",
	"qkdoc: 已写入 %s（%d 字节）\n":                                        "qkdoc: wrote %s (%d bytes)\n",
	"qkrepl: -e 需要一段代码":                                             "qkrepl: -e requires a code snippet",
	"qkrepl: 未知参数 %s\n":                                             "qkrepl: unknown argument %s\n",
	"qkrepl %s —— QuarkLang 交互式求值（:help 帮助，:quit 退出）\n":             "qkrepl %s — QuarkLang interactive evaluation (:help for help, :quit to exit)\n",
	"  QuarkLang API 文档生成：/* */ 与 // 注释 + pub 导出 → Markdown / HTML": "  QuarkLang API doc generator: /* */ and // comments + pub exports -> Markdown / HTML",
	"  QuarkLang 交互式求值：多行块、跨输入持久环境、:help/:load/:quit":               "  QuarkLang interactive evaluation: multi-line blocks, persistent environment, :help/:load/:quit",
	"  QuarkLang 静态检查（QK101–QK115）：未使用变量/形参/导入/函数 · 不可达代码 · 遮蔽 · 缺返回 ·":           "  QuarkLang static analysis (QK101-QK115): unused variable/parameter/import/function, unreachable code, shadowing, missing return,",
	"                           接口近失配 · void 误用 · 自赋值 · 常量条件 · 常量除零 · 死存储 · 自身比较": "                           interface near-miss, void misuse, self-assignment, constant condition, constant divide-by-zero, dead store, self-comparison",
	"变量": "variable",
	"  QuarkLang 静态检查（QK101–QK115）：未使用变量/形参/导入/函数 · 不可达代码 · 遮蔽 · 缺返回 ·\n                           接口近失配 · void 误用 · 自赋值 · 常量条件 · 常量除零 · 死存储 · 自身比较": "  QuarkLang static analysis (QK101-QK115): unused vars/params/imports/functions, unreachable code,\n                           shadowing, missing return, interface near-miss, void misuse, self-assign,\n                           constant condition, division by zero, dead store, self-comparison",
}
