package i18n

// Generated by the table split: the typecheck domain translations (Chinese template -> English).
// Keys are the exact templates used at the call sites; TestTemplatesRegistered fails when one is missing.
var typecheckTable = map[string]string{

	"CompileError: duplicate overload %q (与已有签名相同)":                              "CompileError: duplicate overload %q (identical signature already exists)",
	"TypeError: get(i) 需要 int 下标，得到 %s":                                          "TypeError: get(i) requires an int index, got %s",
	"TypeError: substring(start, end?) 需要 1-2 个 int 参数":                          "TypeError: substring(start, end?) requires one or two int arguments",
	"TypeError: substring 参数必须是 int":                                             "TypeError: substring arguments must be ints",
	"TypeError: file 没有方法 %q":                                                    "TypeError: file has no method %q",
	"TypeError: %s 需要 String 参数":                                                 "TypeError: %s requires a String argument",
	"TypeError: qkhttp_post(url, body, contentType) 全部为 String":                  "TypeError: qkhttp_post(url, body, contentType) requires Strings for all arguments",
	"LibraryError: 库 %s 没有导出函数 %q":                                               "LibraryError: library %s does not export function %q",
	"LibraryError: %s.%s 需要 %d 个参数，给了 %d":                                        "LibraryError: %s.%s expects %d arguments, got %d",
	"TypeError: %s.%s 参数 %s 需要 %s，给了 %s":                                         "TypeError: %s.%s argument %s requires %s, got %s",
	"TypeError: 未知系统库 %q":                                                        "TypeError: unknown system library %q",
	"TypeError: @styleConfigure 只能包装函数/方法调用":                                     "TypeError: @styleConfigure can only wrap a function or method call",
	"CompileError: @%s —— 签名名必须是作用域中的 Sign 实例变量（名字任意）":                           "CompileError: @%s — the signature name must be a Sign instance variable in scope (any name)",
	"TypeError: sum 第一个参数必须是函数引用，got %s":                                         "TypeError: sum's first argument must be a function reference, got %s",
	"TypeError: sum 的边界参数必须是 int，got %s":                                         "TypeError: sum's bound arguments must be ints, got %s",
	"CompileError: sum(generate, begin, stop[, step]) 需要 3 或 4 个参数，got %d":       "CompileError: sum(generate, begin, stop[, step]) requires 3 or 4 arguments, got %d",
	"TypeError: bitwise and shift operators require int operands, got %s and %s": "TypeError: 位运算与移位运算需要 int 操作数，got %s and %s",
	"TypeError: the bitwise complement '~' requires an int operand, got %s":      "TypeError: 取反运算符 '~' 需要 int 操作数，got %s",
	"接口 %s 缺少 %s 的方法 %q":                                                         "interface %s is missing method %q of %s",
	"接口 %s 的方法 %q 与 %s 的签名不兼容（按类型严格）":                                            "interface %s method %q is signature-incompatible with %s (strict by type)",
	"未知接口 %s":                                                "unknown interface %s",
	"类型 %s 未实现接口方法 %q":                                       "type %s does not implement interface method %q",
	"TypeError: %s 没有字段 %q":                                  "TypeError: %s has no field %q",
	"TypeError: 字段 %q: cannot assign %s to %s":               "TypeError: field %q: cannot assign %s to %s",
	"TypeError: %s 需要 %d 个字段，字面量给了 %d":                       "TypeError: %s requires %d fields but the literal provides %d",
	"TypeError: for 迭代变量类型 %s 与元素类型 %s 不匹配":                  "TypeError: for-loop variable type %s does not match element type %s",
	"CompileError: break 只能在 while/for 循环体内":                 "CompileError: break is only allowed inside while/for loops",
	"CompileError: const 变量 %q 不可重新赋值":                       "CompileError: const variable %q cannot be reassigned",
	"TypeError: 索引键需要 %s，给了 %s":                              "TypeError: index key must be %s, got %s",
	"TypeError: 值需要 %s，给了 %s":                                "TypeError: value must be %s, got %s",
	"TypeError: no member %q on 匿名结构体":                       "TypeError: no member %q on an anonymous struct",
	"TypeError: 未知接口 %q":                                     "TypeError: unknown interface %q",
	"TypeError: %s.%s 需要 %d 个参数，给了 %d":                       "TypeError: %s.%s expects %d arguments, got %d",
	"TypeError: 接口 %s 没有方法 %q":                               "TypeError: interface %s has no method %q",
	"CompileError: %s expects %d args (可加 retries), got %d":  "CompileError: %s expects %d args (optionally plus retries), got %d",
	"sum(generate, begin, stop[, step]) 需要 3 或 4 个参数，got %d": "sum(generate, begin, stop[, step]) requires 3 or 4 arguments, got %d",
	"接口 %s 没有方法 %q":                                          "interface %s has no method %q",

	// Expression depth: the shared front end refuses a nesting deeper than its limit instead of
	// exhausting the Go stack, so both engines report a position rather than dying.
	"CompileError: expression nesting is deeper than %d levels, the limit of this implementation: split the expression into smaller statements": "CompileError: 表达式嵌套深度超过本实现的 %d 层上限：请把表达式拆成更小的语句",

	// Raw bits (bit / bits<N>) and the uchar view: the operator, indexing and conversion rules of spec §3.
	"CompileError: bit index %d is out of range for %s (0..%d)":                                                                                            "CompileError: 位下标 %d 超出 %s 的范围 (0..%d)",
	"TypeError: a bit index must be int, got %s":                                                                                                           "TypeError: 位下标必须是 int，得到 %s",
	"TypeError: cannot assign %s to %s[i] (%s)":                                                                                                            "TypeError: 不能把 %s 赋给 %s[i]（%s）",
	"TypeError: raw bits admit no arithmetic: '%s' on %s — convert to a view first, e.g. int(b) %s 1 (spec §3.3)":                                          "TypeError: 原始位不支持算术：'%s' 作用于 %s —— 请先转换为视图，例如 int(b) %s 1（规范 §3.3）",
	"TypeError: raw bits admit no ordering: '%s' on %s — convert to a view first, e.g. int(b) %s 1 (spec §3.3)":                                            "TypeError: 原始位不支持比较大小：'%s' 作用于 %s —— 请先转换为视图，例如 int(b) %s 1（规范 §3.3）",
	"TypeError: raw bits admit only & | ^ ~ << >> == != and b[i], not '%s' (spec §3.3)":                                                                    "TypeError: 原始位只支持 & | ^ ~ << >> == != 和 b[i]，不支持 '%s'（规范 §3.3）",
	"TypeError: %s and %s have different widths (%d and %d bits): a bitwise operation needs equal widths (spec §3.4)":                                      "TypeError: %s 与 %s 宽度不同（%d 位与 %d 位）：位运算要求两侧宽度相同（规范 §3.4）",
	"TypeError: %s needs a shift count of int or raw bits, got %s":                                                                                         "TypeError: %s 的移位次数需要 int 或原始位，得到 %s",
	"TypeError: %s on %s and %s mixes raw bits with a view: both sides must be raw bits of one width (spec §3.3)":                                          "TypeError: %s 作用于 %s 与 %s：原始位与视图混用，两侧必须是同宽度的原始位（规范 §3.3）",
	"TypeError: %s shifts raw bits, so the left operand must be raw bits, got %s":                                                                          "TypeError: %s 是原始位的移位，左操作数必须是原始位，得到 %s",
	"TypeError: %s(%s) is a width mismatch: %s is %d bits wide and %s is %d bits wide (spec §3.4)":                                                         "TypeError: %s(%s) 宽度不匹配：%s 为 %d 位，%s 为 %d 位（规范 §3.4）",
	"TypeError: %s(%s) is not a conversion: a reinterpretation needs a view of the same width, and a value conversion needs two integer views (spec §3.4)": "TypeError: %s(%s) 不是转换：重解释需要同宽度的视图，值转换需要两个整数视图（规范 §3.4）",
}
