package i18n

// Generated by the table split: the docgen domain translations (Chinese template -> English).
// Keys are the exact templates used at the call sites; TestTemplatesRegistered fails when one is missing.
var docgenTable = map[string]string{

	"> 形态：`program ": "> Form: `program ",
	"　·　导入：":         " · imports: ",
	"_（没有可导出的符号）_":   "_(no exported symbols)_",
	"## 概览\n\n| 类别 | 名称 | 签名 | 摘要 |\n|---|---|---|---|\n": "## Overview\n\n| Kind | Name | Signature | Summary |\n|---|---|---|---|\n",
	"| 字段 | 类型 | 说明 |\n|---|---|---|\n":                   "| Field | Type | Description |\n|---|---|---|\n",
	"| 成员 | 签名 | 说明 |\n|---|---|---|\n":                   "| Member | Signature | Description |\n|---|---|---|\n",
	"_（没有可导出的符号）_\n":                                      "_(no exported symbols)_\n",
}
