package i18n

// Generated by the table split: the macro domain translations.
// Legacy keys are Chinese templates carrying their English value; new messages are English source
// carrying their Chinese value (the migration direction the coverage ratchet freezes).
// Keys are the exact templates used at the call sites; TestTemplatesRegistered fails when one is missing.
var macroTable = map[string]string{

	"ParseError: #macro is not the standard spelling (STANDARD 6.6): write macro name($a $b) { ... }, line %d": "ParseError: #macro 不是规范写法（STANDARD 6.6）：请写 macro name($a $b) { ... }，第 %d 行",
	"ParseError: macro needs a name, line %d":                                                   "ParseError: macro 需要名字，第 %d 行",
	"ParseError: macro %s is missing its ($name) parameter list, line %d":                       "ParseError: macro %s 缺少 ($形参) 参数列表，第 %d 行",
	"ParseError: macro %s parameters are written $name (one or more, space-separated), line %d": "ParseError: macro %s 的参数写作 $名字（一个或多个，空格分隔），第 %d 行",
	"ParseError: macro %s needs at least one $name parameter, line %d":                          "ParseError: macro %s 至少需要一个 $名字 参数，第 %d 行",
	"ParseError: macro %s body must be a { ... } block, line %d":                                "ParseError: macro %s 的主体必须是 { ... } 块，第 %d 行",
	"ParseError: $ must be followed by a parameter name, line %d":                               "ParseError: $ 后必须是参数名，第 %d 行",
	"ParseError: $%s is not a parameter of this macro, line %d":                                 "ParseError: $%s 不是这个宏的参数，第 %d 行",
	"ParseError: 分隔符不配对，第 %d 行":                                                                 "ParseError: unbalanced delimiters, line %d",
	"ParseError: 宏 %s 需要 %d 个参数，调用给了 %d 个（第 %d 行）":                                              "ParseError: macro %s expects %d parameters but the call passed %d, line %d",
	"宏 %s 展开失败：%v":                                                                              "macro %s failed to expand: %v",
	"第 %d 行：# 后必须是预处理命令（when/return/error）":                                                     "line %d: '#' must be followed by a preprocessor command (when/return/error)",
	"第 %d 行：#%s 需要 ( ... )":                                                                     "line %d: #%s requires ( ... )",
	"第 %d 行：#when 需要 (compile|run)":                                                             "line %d: #when requires (compile|run)",
	"第 %d 行：#when 需要 { ... } 块":                                                                 "line %d: #when requires a { ... } block",
	"第 %d 行：#error 需要 (\"消息\")":                                                                 "line %d: #error requires (\"message\")",
	"第 %d 行：预处理错误 #error(%s)":                                                                   "line %d: #error(%s)",
	"第 %d 行：#insert(#ast(%s))：%s 不是宏参数名":                                                        "line %d: #insert(#ast(%s)): %s is not a macro parameter name",
	"第 %d 行：#execute 需要 (名字)":                                                                   "line %d: #execute requires (name)",
	"第 %d 行：未知预处理命令 #%s":                                                                        "line %d: unknown preprocessor command #%s",
	"#insert 需要 (#ast($名字)) 形式":                                                                 "#insert requires the (#ast($name)) form",
}
