package i18n

// Generated by the table split: the lexer domain translations (Chinese template -> English).
// Keys are the exact templates used at the call sites; TestTemplatesRegistered fails when one is missing.
var lexerTable = map[string]string{

	"实名结构体必须写 type：type struct { ... } %s;":                      "a named struct requires 'type': type struct { ... } %s;",
	"实名接口必须写 type：type interface { ... } %s;":                    "a named interface requires 'type': type interface { ... } %s;",
	"library 体内只能有 fn 符号签名":                                      "a library body may only contain fn symbol signatures",
	"program 声明只支持 main / library（lib）":                          "program declarations support only main / library (lib)",
	"重复的 program 预制宏":                                            "duplicate program preprocessor macro",
	"pub 的匿名结构体没有名字可导出：pub type struct { ... } Name;":            "an anonymous struct has no name to export: pub type struct { ... } Name;",
	"pub 的匿名接口没有名字可导出：pub type interface { ... } Name;":          "an anonymous interface has no name to export: pub type interface { ... } Name;",
	"pub type 只支持 struct / interface":                            "pub type supports only struct / interface",
	"pub 只能前缀于 fn 或 type struct/interface（实名类型必须写 type）":         "pub may only prefix fn or type struct/interface (named types require 'type')",
	"函数声明关键字是 fn：func main(...) 应写为 fn main(...)":                "the function keyword is 'fn': write fn main(...) rather than func main(...)",
	"函数必须声明返回类型：fn %s(...) 返回类型 { ... }":                         "a function must declare its return type: fn %s(...) <return type> { ... }",
	"匿名 struct 类型不支持泛型参数（请写 type struct<T> { ... } Name;）":       "an anonymous struct cannot take generic parameters (write type struct<T> { ... } Name;)",
	"匿名 interface 类型不支持泛型参数（请写 type interface<T> { ... } Name;）": "an anonymous interface cannot take generic parameters (write type interface<T> { ... } Name;)",

	// Parser nesting: an over-deep descent is refused instead of exhausting the Go stack, so the engine
	// reports a position rather than dying.
	"nesting is deeper than %d levels, the limit of this implementation: split the expression into smaller statements": "嵌套深度超过本实现的 %d 层上限：请把表达式拆成更小的语句",
}
