package cgen

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// parityCases returns compiler/testdata/cases/*.kq (the test working directory is internal/cgen).
// These cases use only libc + the in-module ql_strcat, so lli can run them directly.
func parityCases(t *testing.T) []string {
	t.Helper()
	files, err := filepath.Glob(filepath.Join("..", "..", "testdata", "cases", "*.kq"))
	if err != nil || len(files) == 0 {
		t.Fatalf("no parity cases found: %v", err)
	}
	return files
}

// parityRunCases returns compiler/testdata/cases_run/*.kq: these need clang linking (library FFI
// wants -lm/-lc, taskm wants the qthreads runtime), so only IR syntax is checked; end-to-end is
// compared byte for byte against the interpreter by compiler/testdata/compare.sh (qkc -run).
func parityRunCases(t *testing.T) []string {
	t.Helper()
	files, err := filepath.Glob(filepath.Join("..", "..", "testdata", "cases_run", "*.kq"))
	if err != nil || len(files) == 0 {
		t.Fatalf("no run parity cases found: %v", err)
	}
	return files
}

// TestParityCaseIRSyntax checks that the IR generated for every parity case passes LLVM's official syntax check.
func TestParityCaseIRSyntax(t *testing.T) {
	llvmAs, err := exec.LookPath("llvm-as")
	if err != nil {
		t.Skip("llvm-as not available")
	}
	all := append(parityCases(t), parityRunCases(t)...)
	for _, f := range all {
		t.Run(filepath.Base(f), func(t *testing.T) {
			src, err := os.ReadFile(f)
			if err != nil {
				t.Fatal(err)
			}
			ir, err := Transpile(string(src), f)
			if err != nil {
				t.Fatalf("Transpile: %v", err)
			}
			tmp, err := os.CreateTemp("", "quark-parity-*.ll")
			if err != nil {
				t.Fatal(err)
			}
			defer os.Remove(tmp.Name())
			if _, err := tmp.WriteString(ir); err != nil {
				t.Fatal(err)
			}
			tmp.Close()
			if out, err := exec.Command(llvmAs, tmp.Name(), "-o", os.DevNull).CombinedOutput(); err != nil {
				t.Fatalf("llvm-as rejected IR: %v\n%s\nIR:\n%s", err, out, ir)
			}
		})
	}
}

// TestParityCaseOutput runs each case with lli and compares byte for byte against the .out produced by the interpreter.
// The .out files are generated by the interpreter (compiler/testdata/compare.sh rechecks that the two agree).
func TestParityCaseOutput(t *testing.T) {
	if _, err := exec.LookPath("lli"); err != nil {
		t.Skip("lli not available")
	}
	for _, f := range parityCases(t) {
		t.Run(filepath.Base(f), func(t *testing.T) {
			src, err := os.ReadFile(f)
			if err != nil {
				t.Fatal(err)
			}
			want, err := os.ReadFile(strings.TrimSuffix(f, ".kq") + ".out")
			if err != nil {
				t.Fatalf("missing expected output fixture: %v", err)
			}
			ir, err := Transpile(string(src), f)
			if err != nil {
				t.Fatalf("Transpile: %v", err)
			}
			got := lliRun(t, withTestRuntime(ir))
			if got != string(want) {
				t.Fatalf("output mismatch\n got: %q\nwant: %q", got, string(want))
			}
		})
	}
}
