#!/usr/bin/env bash
# Generate a changelog from git history (grouped by type), for GitHub Release notes and CHANGELOG.md.
#
# Usage: scripts/changelog.sh [version] [start ref]
#   scripts/changelog.sh 0.3.0            # since the previous tag -> "## 0.3.0 - date"
#   scripts/changelog.sh 0.3.0 v0.2.0     # explicit start ref
#   scripts/changelog.sh --all            # full history (split per tag)
set -euo pipefail

cd "$(dirname "$0")/.."

# emit_commits <range>: bucket commits by keyword (repository commit subjects are free-form Chinese).
emit_commits() {
  local range="$1"
  local log
  log="$(git log --no-merges --pretty=format:'%h %s' $range 2>/dev/null || true)"
  if [ -z "$log" ]; then
    echo "_(no commits)_"
    echo
    return
  fi
  # NOTE: the match patterns keep their Chinese keywords on purpose - they must go on matching the
  # existing (Chinese) commit subjects in this repository's history, so the grouping stays stable.
  local groups=("新功能|首发|新增|接入|支持|实现|feat"
                "修复|修复|修正|修 |bug|fix|回归"
                "性能|性能|优化|提速|perf"
                "重构与清理|重构|清理|剥离|卫生|死代码|refactor"
                "文档|文档|README|SYNTAX|注释|docs"
                "构建与工具链|CI|workflow|构建|发布|版本|脚本|依赖|测试")
  local titles=("Features" "Fixes" "Performance" "Refactoring & cleanup" "Docs" "Build & toolchain")
  local assigned=()
  local i
  for i in "${!groups[@]}"; do
    local pattern="${groups[$i]}"
    local title="${titles[$i]}"
    local lines=""
    while IFS= read -r line; do
      [ -z "$line" ] && continue
      local subject="${line#* }"
      local sha="${line%% *}"
      local skip=0
      local j
      for j in $(seq 0 $((i - 1))); do
        if printf '%s' "$subject" | grep -qE "${groups[$j]}"; then skip=1; break; fi
      done
      [ "$skip" = "1" ] && continue
      if printf '%s' "$subject" | grep -qE "$pattern"; then
        lines+="- ${subject} (\`${sha}\`)"$'\n'
      fi
    done <<< "$log"
    if [ -n "$lines" ]; then
      echo "### ${title}"
      echo
      printf '%s' "$lines"
      echo
    fi
    assigned+=("$lines")
  done

  # Commits that matched no group
  local other=""
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    local subject="${line#* }"
    local sha="${line%% *}"
    local matched=0
    local p
    for p in "${groups[@]}"; do
      if printf '%s' "$subject" | grep -qE "$p"; then matched=1; break; fi
    done
    if [ "$matched" = "0" ]; then
      other+="- ${subject} (\`${sha}\`)"$'\n'
    fi
  done <<< "$log"
  if [ -n "$other" ]; then
    echo "### Other"
    echo
    printf '%s' "$other"
    echo
  fi
}

if [ "${1:-}" = "--all" ]; then
  echo "# Changelog"
  echo
  echo "> Generated by \`scripts/changelog.sh --all\` from git history (groups: Features / Fixes / Performance / Refactoring & cleanup / Docs / Build & toolchain / Other)."
  echo
  prev=""
  for tag in $(git tag --sort=creatordate); do
    echo "## ${tag}"
    echo
    emit_commits "${prev:+${prev}..}${tag}"
    prev="$tag"
  done
  if [ -n "$prev" ]; then
    echo "## Unreleased (after ${prev})"
    echo
    emit_commits "${prev}..HEAD"
  fi
  exit 0
fi

ARG="${1:-$(cat VERSION 2>/dev/null || echo unreleased)}"
DATE="$(date -u '+%Y-%m-%d')"

# Range derivation (the release workflow runs on the tag commit, which is the easiest place to trip up):
#   - an explicit start ($2) was given -> use it, end at HEAD;
#   - otherwise, if HEAD is exactly on a tag -> start at **its previous tag**, end at that tag
#     (a plain `git describe --abbrev=0` returns the current tag, so "<tag>..HEAD" is empty -> "no commits" in the release notes);
#   - anything else -> start at the nearest tag, end at HEAD.
END="HEAD"
if [ -n "${2:-}" ]; then
  START="$2"
else
  cur="$(git describe --tags --exact-match 2>/dev/null || true)"
  if [ -n "$cur" ]; then
    START="$(git describe --tags --abbrev=0 "${cur}^" 2>/dev/null || true)"
    END="$cur"
  else
    START="$(git describe --tags --abbrev=0 2>/dev/null || true)"
  fi
fi

echo "## ${ARG} - ${DATE}"
echo
emit_commits "${START:+${START}..}${END}"
